#!/bin/bash

DATABASE="afranco_wordpress_miis"
URI="/~afranco/wordpress"
DEST_FILE_PATH="/home/afranco/private_html/wordpress/blogs.dir/"

SITES=()

SITES+=("1") # /middblogs THIS IS REQUIRED
SITES+=("720") # afrancotest
SITES+=("813") # /wip


# Sync files
RSYNC_CMD="rsync -av ";
for SITE in "${SITES[@]}"
do
	RSYNC_CMD+="--include=\"${SITE}/***\" "
done
RSYNC_CMD+=" --exclude=\"*\" bigsur:/var/www/wordpress-mu/wp-content/blogs.dir/ $DEST_FILE_PATH"

echo "Syncing files"
echo $RSYNC_CMD
eval $RSYNC_CMD


TABLES=()
PREFIXES=()
for SITE in "${SITES[@]}"
do
	PREFIXES+=("wp_${SITE}_")
done

TABLELIST=$(mysql -h snipe -u wpmiis -pxxxxx miiswp -e "show tables;" | awk '{ print $1}' | grep -v '^Tables')
for i in $TABLELIST
do
	# Add non-individual-blog tables
	if [[ $i =~ ^wp_[a-z] ]]
	then
		TABLES+=($i)
	fi

	# Add tables of our chosen blogs
	for PREFIX in "${PREFIXES[@]}"
	do
		if [[ $i == $PREFIX* ]]
		then
			TABLES+=($i)
		fi
	done
done

echo "Tables being dumped:"
echo ${TABLES[@]}
mysqldump -h snipe -u wpmiis -pxxxxxx miiswp --set-gtid-purged=OFF --lock-tables=false --skip-extended-insert ${TABLES[@]} > $DATABASE.sql

echo "Swapping paths"
perl -p -i -e "s#http://sites.miis.edu#http://anvil.middlebury.edu$URI#gi" $DATABASE.sql
perl -p -i -e 's#sites.miis.edu#anvil.middlebury.edu#gi' $DATABASE.sql
perl -p -i -e "s#anvil\.middlebury\.edu','/#anvil.middlebury.edu','$URI/#gi" $DATABASE.sql

echo "Importing data from for $DATABASE into local database"
mysql -u testuser -ptestpassword -h localhost $DATABASE < $DATABASE.sql

rm -f $DATABASE.sql


# Add tables of our chosen blogs
for PREFIX in "${PREFIXES[@]}"
do
	if [[ $i == $PREFIX* ]]
	then
		wp_update_settings_miis "${PREFIX}options"
	fi
done

