#!/bin/env php
<?php

$usage = <<<END
Usage: $argv[0] <file.ini> <section> <variable>

END;

if (empty($argv[1]) || empty($argv[2]) || empty($argv[3]) || count($argv) > 4) {
	fwrite(STDERR, $usage);
	exit(1);
}

$ini = parse_ini_file($argv[1], true);

if (!isset($ini[$argv[2]])) {
	fwrite(STDERR, "section, [".$argv[2]."], was not found in the ini file.\n");
	exit(2);
}

if (!isset($ini[$argv[2]][$argv[3]])) {
	fwrite(STDERR, "variable, ".$argv[3].", was not found in the [".$argv[2]."] section of the ini file.\n");
	exit(3);
}
print $ini[$argv[2]][$argv[3]]."\n";